# Toy data generated by Dirichlet distribution

library(pracma) # to use logspace, logseq function

# Generate the same data as in python example
library(reticulate)
use_python("/home/users/pjywang/miniconda3/envs/R/bin/python3.11") # your python.exe file path
np <- import("numpy")

source(file = './CoDA-Penalized-Regression/R/functions_coda_penalized_regression.R')
source(file = './CoDA-Penalized-Regression/R/functions.R')
source(file = './selbal/R/Selbal_Functions.R')
source(file = './selbal/R/data.R')
source(file = './tools.R')

a1 = rep(1, 10)
a2 = rep(1, 10)
a2[6:7] = 3

# Same data generation as the example code in ccm_coda.py
np$random$seed(as.integer(77))
x1 = np$random$dirichlet(a1, as.integer(25))
x2 = np$random$dirichlet(a2, as.integer(25))
x = rbind(x1, x2)
colnames(x) <- seq(1, 10)
y = as.factor(c(rep(0, 25), rep(1, 25)))


## Coda-lasso

lambdaRange_codalasso(y, x, lambdaSeq = seq(0.1, 0.5, 0.01))  # to find appropriate lambda range

model <- coda_logistic_lasso(y, x, lambda=0.29)
model$`name of selected variables` # 2, 6 are selected

# coda-lasso doesn't find the true signal "7"




## Selbal

model_selbal <- selbal(x, y, maxV = 10)
result_selbal <- selbal_wrapper(model_selbal, x)
result_selbal$varIndex # 2, 4, 6, 8 are selected

# selbal also doesn't find the true signal "7"


